---

- name: Playbook to install kubevirt
  hosts: kubevirt_hosts
  collections:
    - kcd.kubevirt
    - kcd.k8s
  tasks:
    - name: Install K8s with kubeadm
      ansible.builtin.import_role:
        name: single_node
    - name: Install Kubevirt
      ansible.builtin.import_role:
        name: kubevirt
    - name: Install Service Mesh
      ansible.builtin.import_role:
        name: service_mesh
