---

- name: Create namespace for Jeager
  kubernetes.core.k8s:
    state: present
    kind: Namespace
    name: "{{ item }}"
    kubeconfig: /etc/kubernetes/admin.conf
  become: true
  loop:
    - elastic-system
    - jaeger-system

- name: Add helm repository for elastic Search
  kubernetes.core.helm_repository:
    name: elastic
    url: https://helm.elastic.co
    kubeconfig: /etc/kubernetes/admin.conf
  become: true

- name: Install elastic Search
  kubernetes.core.helm:
    name: elastic
    chart_ref: elastic/elasticsearch
    release_name: elastic
    release_namespace: elastic-system
    state: present
    kubeconfig: /etc/kubernetes/admin.conf
    values:
      service:
        type: NodePort
      replicas: 1
      volumeClaimTemplate:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 40Gi
        storageClassName: topolvm-provisioner
        volumeMode: Filesystem
  become: true

- name: Install kibana
  kubernetes.core.helm:
    name: kibana
    chart_ref: elastic/kibana
    release_name: kibana
    release_namespace: elastic-system
    state: present
    kubeconfig: /etc/kubernetes/admin.conf
    values:
      service:
        type: NodePort
  become: true

- name: Add jaeger helm repository
  kubernetes.core.helm_repository:
    name: jaegertracing
    url: https://jaegertracing.github.io/helm-charts
    kubeconfig: /etc/kubernetes/admin.conf
  become: true

- name: Install jaeger
  kubernetes.core.helm:
    name: jaeger
    chart_ref: jaegertracing/jaeger
    release_name: jaeger
    release_namespace: jaeger-system
    state: present
    kubeconfig: /etc/kubernetes/admin.conf
    values:
      provisionDataStore:
        elasticsearch: true
        cassandra: false
      agent:
        strategy: DaemonSet
      collector:
        strategy: DaemonSet
      query:
        strategy: Deployment
      storage:
        type: elasticsearch
        elasticsearch:
          host: elastic-client
          port: 9200
          indexPrefix: jaeger
          tls:
            enabled: false
  become: true