---
- name: Create  namespace for cert-manager
  kubernetes.core.k8s:
    state: present
    kind: Namespace
    name: cert-manager
    kubeconfig: /etc/kubernetes/admin.conf
  become: true

- name: Add helm repository for cert-manager
  kubernetes.core.helm_repository:
    name: jetstack
    url: https://charts.jetstack.io
    kubeconfig: /etc/kubernetes/admin.conf
  become: true

- name: Install cert-manager
  kubernetes.core.helm:
    name: cert-manager
    chart_ref: jetstack/cert-manager
    release_name: cert-manager
    release_namespace: cert-manager
    state: present
    kubeconfig: /etc/kubernetes/admin.conf
    wait: true
  become: true