#SPDX-License-Identifier: MIT-0
---

- name: Install Istio
  ansible.builtin.import_tasks:
    file: install_istio.yaml

#- name: Install cert manager
#  ansible.builtin.import_tasks:
#    name: install-cert-manager.yaml

- name: Install jeager
  ansible.builtin.import_tasks:
    file: install_jaeger.yaml
  tags: jaeger
