---

- name: Create namespace for prometheus
  kubernetes.core.k8s:
    state: present
    kind: Namespace
    name: prometheus
    kubeconfig: /etc/kubernetes/admin.conf
  become: true

- name: Add helm repository for prometheus
  kubernetes.core.helm_repository:
    name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
    kubeconfig: /etc/kubernetes/admin.conf
  become: true

- name: Install prometheus
  kubernetes.core.helm:
    name: prometheus
    chart_ref: prometheus-community/prometheus
    release_name: prometheus
    release_namespace: prometheus
    state: present
    kubeconfig: /etc/kubernetes/admin.conf
    values:
      alertmanager:
        persistence:
          storageClass: "topolvm-provisioner"
      server:
        persistentVolume:
          storageClass: "topolvm-provisioner"
  become: true

    