#SPDX-License-Identifier: MIT-0
---

- name: Install nfs
  ansible.builtin.import_tasks:
    file: install_nfs.yaml
  tags: nfs

- name: Install K8s with kubeadm
  ansible.builtin.import_tasks:
    file: install_k8s.yaml

- name: Install services for k8s
  ansible.builtin.import_tasks:
    file: install_services.yaml

- name: Configure topolvm
  ansible.builtin.import_tasks:
    file: install_topolvm.yaml
  tags: topolvm

- name: Install prometheus
  ansible.builtin.import_tasks:
    file: install_prometheus.yaml
  tags: prometheus